# Generated by Django 2.1.7 on 2019-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='python', max_length=20),
            preserve_default=False,
        ),
    ]
