# Generated by Django 2.1.7 on 2019-03-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.URLField(default='www.github.com/paulojenks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
