# Generated by Django 2.1.7 on 2019-03-30 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_auto_20190317_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
