# Generated by Django 2.1.7 on 2019-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0005_auto_20190330_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
