# Generated by Django 2.1.7 on 2019-05-11 04:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_portfolio', '0006_auto_20190331_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('first_name', models.CharField(max_length=44)),
                ('last_name', models.CharField(max_length=44)),
                ('personal_bio', models.TextField()),
                ('professional_bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
